# Generated by Django 5.1.15 on 2026-03-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aso', '0006_alter_searchresult_popularity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS / iPadOS'), ('macos', 'macOS')], default='ios', help_text='Target platform', max_length=10),
        ),
    ]
